version: '3.8'
services:
  lottery-app:
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
